### PR TITLE
feat: added ability to provide functions as parameter route handlers

### PR DESCRIPTION
**Pull request by bsara**
There are times when it would be useful to have a custom function for a route handler only configured on a single story. Currently, the only way to provide a function for route handling is in the "makeServer" function that is generally created to initialize a server. This PR adds the ability to also provide function route handlers via the `parameters`.

Example Potential Usage:

```javascript
export default {
  // ...
  parameters: {
    mirage: {
      // ...
      handlers: {
        get: {
          '/api/user/:id': (schema, req) => {
            const idAsNum = Number(req.params.id);

            return (
              (!Number.isNaN(idAsNum) && idAsNum >= 400)
                ? new Response(idAsNum, {}, null)
                : new Response(200, {}, {
                  id: req.params.id,
                  name: faker.person.fullName()
                }
            );
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Review by HipsterBrown — APPROVED** [review]
Thanks for contributing, this looks great!

**Comment by HipsterBrown** [comment]
@bsara Your update has been included in the v0.3.0 release with the upgrade to Storybook 8 since I needed to fix the GitHub Workflow first.

**Comment by bsara** [comment]
Cool beans. Thanks!

**Comment by bsara** [comment]
@HipsterBrown whoops, i just realized that I left my work email on my commits and that ended up in the release description of 0.3.0. would it be too much trouble to ask that you remove that email address from there for me?

**Comment by HipsterBrown** [comment]
@bsara Done!

**Comment by bsara** [comment]
Thanks so much!

**Pull request merged**
