### PR TITLE
Allow stories to seed their own data using the factories defined within the makeServer function.

### PR DESCRIPTION
**Pull request by daves28**
This PR allows a story to seed its own data based on factories in the server.

To do so it would look like this:
```
Story.parameters = {
  mirage: {
    logging: true,
    handlers: {...},
    factorySeeds: {
        // create 2 addresses with the same traits.
        address: [{ traits: ['withRecipient', 'withCompleteAddress'], count: 2 }],
        // create a single cart item with no specific traits
        cart: [{}],
        // create 2 users that contain override values
        user: [
          {
            traits: [
              'withSomeTrait',
              'withOtherTrait',
              // override certain values
              {
                name: 'R2D2',
                gender: 'Male',
              },
            ],
          },
          {
            traits: [
              'withSomeTrait',
              'withOtherTrait',
              {
                name: 'BB8',
                gender: 'Male',
              },
            ],
          },
        ],
    },
  },
};
```
Where the name of the property corresponds to one of the factories, and value is an array of items with 1. traits as an array of trait names (defined within that factory in makeServer) or an object of data to pass in specific override values and 2. a count property to indicate how many of that type of item should be created, defaulting to 1.

### CODE REVIEW

**Comment by daves28** [comment]
Another choice may be to create a `seeds` property which has both `fixtures` and `factories` nested under it rather than have them both be top level properties.

**Review by HipsterBrown — COMMENTED** [review]
Thanks for opening a PR! :clap: This looks like a really useful addition. 

Could you add an example of how to use this in one of the `stories/` for the demo storybook?

**Comment by daves28** [comment]
@HipsterBrown Added an example. Let me know if you'd like me to change anything. I was pretty light on the styling but I can add more if you prefer. Thanks for taking a look!

**Review by HipsterBrown — APPROVED** [review]
Thanks for adding the example story and clearing up the added documentation. 💯

**Comment by daves28** [comment]
Added more styling to make it look like your Page story :). Thanks for approving

**Pull request merged**
